name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types:
      - created

env:
  ESM_NAME: "@mtrh/esm-patient-dashboard-app"
  JS_NAME: "mtrh-esm-patient-dashboard-app.js"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run lint
      - run: npm run coverage
      - run: npm run typescript
      - run: npm run build --if-present
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist

  deploy:
    runs-on: ubuntu-latest

    needs: build

    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Compute Timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Prepare Directory
        shell: bash
        run: |
          mkdir -p dist/${{ env.ESM_NAME }}/${{ env.TIMESTAMP }}_${{ github.sha }}
          mv dist/*.* dist/${{ env.ESM_NAME }}/${{ env.TIMESTAMP }}_${{ github.sha }}/
      - uses: idlefingers/do-space-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: 'dist'
          SPACE_NAME: ${{ secrets.SPACE_NAME }}
          SPACE_REGION: ${{ secrets.SPACE_REGION}}
          SPACE_ACCESS_KEY_ID: ${{ secrets.SPACE_ACCESS_KEY_ID }}
          SPACE_SECRET_ACCESS_KEY: ${{ secrets.SPACE_SECRET_ACCESS_KEY }}
