name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install lerna -g
      - run: lerna bootstrap
      - run: cd packages/esm-home && npm install && /home/runner/work/cardiology/cardiology
      - run: cd packages/esm-login && npm install && /home/runner/work/cardiology/cardiology
      - run: cd packages/esm-patient-dashboard && npm install && /home/runner/work/cardiology/cardiology
      - run: lerna run typescript
      - run: lerna run test
      - run: lerna run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            packages/**/dist
